-- Apache Derby DDL for TrabajoPPI
-- Tables based on JPA entities:
-- - com.tdea.entities.Ropa
-- - com.tdea.entities.Calzado

CREATE TABLE ROPA (
  ID INT NOT NULL PRIMARY KEY,
  TIPO VARCHAR(50) NOT NULL,
  COLOR VARCHAR(30) NOT NULL,
  TALLA VARCHAR(10) NOT NULL,
  CANTIDAD INT NOT NULL,
  PRECIO DOUBLE NOT NULL
);

CREATE TABLE CALZADO (
  ID INT NOT NULL PRIMARY KEY,
  MARCA VARCHAR(50) NOT NULL,
  TALLA INT NOT NULL,
  COLOR VARCHAR(50) NOT NULL,
  CANTIDAD INT NOT NULL,
  PRECIO DOUBLE NOT NULL
);
